import 'package:drift/drift.dart';

/// A UUID text primary key.
///
/// AoiLoop uses UUIDs rather than autoincrementing integers because the
/// roadmap commits to multi-device sync with caregivers (release 0.2). Two
/// people logging a change offline — a parent at home and a school nurse —
/// would both be handed the same integer id and collide on merge. A UUID is
/// generated on the device that creates the row and stays valid forever, so
/// cross-references like `previousConsumableInstanceId` survive syncing.
///
/// The cost is a wider index. For a personal log measured in thousands of
/// rows, that is not a real cost.
mixin UuidPrimaryKey on Table {
  /// RFC 4122 v4 UUID, generated by `IdGenerator`.
  TextColumn get id => text().withLength(min: 36, max: 36)();

  @override
  Set<Column<Object>> get primaryKey => <Column<Object>>{id};
}

/// Row creation and last-modification instants.
///
/// Both are stored in UTC. Presentation converts to local time; persistence
/// never does. A user who flies to another time zone must not see their
/// history shift.
mixin RowTimestamps on Table {
  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get updatedAt => dateTime()();
}
